-- 完成部分: 定义Definition 2.5.1, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8
-- 引理Lemma 2.5.2, 2.5.12, 2.5.15, 2.5.16的完整证明
-- 引理Lemma 2.5.9, 2.5.11, 2.5.13, 2.5.14, 2.5.17, 2.5.18完成了部分证明, 但仍有一些基础引理需要证明

-- contributor: 张雷智 Def2.5.1, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, Lem2.5.2, 2.5,9, 2.5.12
-- contributor: 罗子宸 Lem2.5.11, 2.5.15, 2.5.16
-- contributor: 代士博 Lem2.5.13, 2.5.14, 2.5.17, 2.5.18

import Mathlib

open BigOperators
open Subgroup

variable (p : ℕ) [Fact p.Prime]

abbrev E (p n : ℕ) [Fact p.Prime] : Type := Multiplicative (Fin n → ZMod p)

-- Definition 2.5.1:
-- We use `exponent ∣ p` to handle the trivial group case (n=0).
-- For non-trivial groups, this implies exponent = p.
variable (G : Type*) [CommGroup G]
def IsElementaryAbelian : Prop :=
  IsPGroup p G ∧ Monoid.exponent G ∣ p



-- Definition 2.5.3: p-rank of elementary abelian p-group
-- The p-rank of E_{p^n} is n
def pRankElementary (p : ℕ) [Fact p.Prime] (G : Type*) [CommGroup G] [Fintype G]
    (h : IsElementaryAbelian p G) : ℕ :=
  Nat.log p (Fintype.card G)

-- Definition 2.5.3: p-rank of a finite group
-- The p-rank of G is the maximal p-rank among all elementary abelian p-subgroups
noncomputable def pRank (p : ℕ) [Fact p.Prime] (G : Type*) [CommGroup G] [Fintype G] : ℕ :=
  ⨆ (H : Subgroup G) (_ : Fintype H) (h : IsElementaryAbelian p H),
    @pRankElementary p _ H _ _ h



-- Definition 2.5.4: Omega_n(G) and Agemo_n(G) for p-groups
variable (G : Type*) [Group G]
-- Omega_n(G): the subgroup generated by {x ∈ G | x^{p^n} = 1}

def Omega (p n : ℕ) (G : Type*) [Group G] : Subgroup G :=
  Subgroup.closure {x : G | x ^ (p ^ n) = 1}

-- Agemo_n(G): the subgroup generated by {x^{p^n} | x ∈ G}
def Agemo (p n : ℕ) (G : Type*) [Group G] : Subgroup G :=
  Subgroup.closure {y : G | ∃ x : G, y = x ^ (p ^ n)}



-- Definition 2.5.5: A group G is called quasi-simple if G = G′ and G/Z(G) is simple.
/- A group G is quasi-simple if it equals its commutator subgroup
   and its quotient by the center is simple -/

variable (G : Type*) [Group G]
def IsQuasiSimple : Prop :=
  commutator G = ⊤ ∧ IsSimpleGroup (G ⧸ Subgroup.center G)



/- Definition 2.5.6: The Fitting subgroup F(G) of a group G is the maximal
   nilpotent normal subgroup of G. -/

variable (G : Type*) [Group G] [Finite G]

-- The Fitting subgroup is the supremum (join) of all nilpotent normal subgroups
def FittingSubgroup (G : Type*) [Group G] : Subgroup G :=
  sSup {H : Subgroup G | H.Normal ∧ Group.IsNilpotent H}

notation "F(" G ")" => FittingSubgroup G

-- The Fitting subgroup is maximal among nilpotent normal subgroups
theorem fittingSubgroup_maximal (H : Subgroup G) (hN : H.Normal) (hNil : Group.IsNilpotent H) :
    H ≤ F(G) := by
  apply le_sSup
  exact ⟨hN, hNil⟩



-- Definition 2.5.7: Critical Subgroup
-- A subgroup H of G is called critical if:
-- 1. Φ(H) ⊂ Z(H) (Frattini subgroup is contained in the center of H)
-- 2. [G, H] ⊂ Z(H) (commutator of G and H is contained in the center of H)
-- 3. C_G(H) = Z(H) (centralizer of H in G equals the center of H)

variable {G : Type*} [Group G]

-- Z(H) is the intersection of H with the centralizer of H in G
def centerOfSubgroup (H : Subgroup G) : Subgroup G :=
  H ⊓ Subgroup.centralizer (H : Set G)

def IsCriticalSubgroup (H : Subgroup G) : Prop :=
  (frattini H).map H.subtype ≤ centerOfSubgroup H ∧
  ⁅(⊤ : Subgroup G), H⁆ ≤ centerOfSubgroup H ∧
  Subgroup.centralizer (H : Set G) = centerOfSubgroup H



-- Definition 2.5.8: A p-group G is called special if Φ(G) = Z(G) = G′
-- where Φ(G) is the Frattini subgroup of G
variable {G : Type*} [Group G]
def IsSpecialPGroup (G : Type*) [Group G] (p : ℕ) [Fact p.Prime] : Prop :=
  IsPGroup p G ∧
  frattini G = Subgroup.center G ∧
  Subgroup.center G = commutator G

-- A p-group is called extra-special if Z(G) is the cyclic group Z/pZ
-- in addition to being special
def IsExtraSpecialPGroup (G : Type*) [Group G] (p : ℕ) [Fact p.Prime] : Prop :=
  IsSpecialPGroup G p ∧
  Nonempty (Subgroup.center G ≃* ZMod p)



-- Lemma 2.5.9: Let G be a solvable group. Then CG(F(G)) ⊂ F(G)
-- The centralizer of the Fitting subgroup is contained in the Fitting subgroup
variable {G : Type*} [Group G] [Finite G]

theorem fittingSubgroup_normal : (F(G)).Normal := by
  sorry

theorem fittingSubgroup_nilpotent : Group.IsNilpotent (F(G)) := by
  sorry

theorem centralizer_normal [Finite G] (H : Subgroup G) [H.Normal] [Group.IsNilpotent ↥H] :
  (centralizer (H : Set G)).Normal := by infer_instance

theorem centralizer_sup_nilpotent [Finite G] (H : Subgroup G) [H.Normal] [Group.IsNilpotent ↥H] :
  Group.IsNilpotent ↥(centralizer (H : Set G) ⊔ H) := by sorry

theorem centralizer_fittingSubgroup_subset_fittingSubgroup
    [IsSolvable G] : centralizer (F(G) : Set G) ≤ F(G) := by
  set F := F(G) with hF_def
  set C := centralizer (F : Set G) with hC_def
  -- F is normal
  haveI hF_normal : F.Normal := fittingSubgroup_normal
  -- F is nilpotent
  haveI hF_nilp : Group.IsNilpotent ↥F := fittingSubgroup_nilpotent
  -- C is normal
  haveI hC_normal : C.Normal := by
    rw [hC_def]
    exact centralizer_normal F
  -- The supremum of two normal subgroups is normal
  haveI h_sup_normal : (C ⊔ F).Normal := inferInstance
  -- C ⊔ F is nilpotent (uses that C centralizes F)
  have h_sup_nilp : Group.IsNilpotent ↥(C ⊔ F) := by
    rw [hC_def]
    exact centralizer_sup_nilpotent F
  -- Therefore C ⊔ F is in the set of normal nilpotent subgroups
  have h_in_set : C ⊔ F ∈ {H : Subgroup G | H.Normal ∧ Group.IsNilpotent ↥H} := by
    exact ⟨h_sup_normal, h_sup_nilp⟩
  -- So C ⊔ F ≤ F(G) by definition of F(G) as the supremum
  have h_le_sSup : C ⊔ F ≤ sSup {H : Subgroup G | H.Normal ∧ Group.IsNilpotent ↥H} := by
    exact le_sSup h_in_set
  -- Since F = F(G), we have C ⊔ F ≤ F
  rw [hF_def] at h_le_sSup
  -- Therefore C ≤ F
  exact le_trans le_sup_left h_le_sSup



-- Lemma 2.5.11: Let G be a non-abelian group of order p^n with a cyclic subgroup of index p.
-- Then G is either modular, dihedral, semidihedral, or quaternion group.

-- Define predicates for the four types of groups
def IsModularGroup (G : Type*) [Group G] : Prop := sorry
def IsDihedralGroup (G : Type*) [Group G] : Prop := sorry
def IsSemiDihedralGroup (G : Type*) [Group G] : Prop := sorry
def IsQuaternionGroup (G : Type*) [Group G] : Prop := sorry

theorem lemma_2_5_11 (G : Type*) [Group G] [Fintype G] (p n : ℕ) [Fact (Nat.Prime p)]
    (h_order : Fintype.card G = p ^ n)
    (h_non_abelian : ∃ (a b : G), a * b ≠ b * a)
    (H : Subgroup G)
    (h_cyclic : IsCyclic H)
    (h_index : H.index = p) :
    IsModularGroup G ∨ IsDihedralGroup G ∨ IsSemiDihedralGroup G ∨ IsQuaternionGroup G := by
  sorry



-- Lemma 2.5.2: Characterization via isomorphism using the Structural Theorem
variable (G : Type*) [CommGroup G]
theorem lemma_2_5_2 [Fintype G] (n : ℕ) :
    (IsElementaryAbelian p G ∧ Fintype.card G = p ^ n)
     ↔ Nonempty (G ≃* E p n) := by
  constructor
  · -- Direction (=>): From Elementary Abelian to (Z/pZ)^n
    rintro ⟨⟨h_pgroup, h_exp⟩, h_card⟩
    -- Step 1: Switch to Additive group to apply the Structural Theorem
    let A := Additive G
    have h_exp_add : AddMonoid.exponent A ∣ p := h_exp
    -- Step 2: Apply the Fundamental Theorem of Finite Abelian Groups
    obtain ⟨ι, h_fin_ι, d, h_d_gt_1, ⟨iso_decomp⟩⟩ :=
      AddCommGroup.equiv_directSum_zmod_of_finite' A
    -- Step 3: Analyze the cyclic components d_i
    have h_components_eq_p : ∀ i, d i = p := by
      classical
      intro i
      -- The exponent of ZMod (d i) is d i
      have h_exp_zmod : AddMonoid.exponent (ZMod (d i)) = d i := ZMod.exponent (d i)
      -- Since iso_decomp is an isomorphism, exponent is preserved
      have h_exp_directsum : AddMonoid.exponent (DirectSum ι fun j => ZMod (d j)) ∣ p := by
        have := AddMonoidHom.exponent_dvd iso_decomp.surjective
        exact dvd_trans this h_exp_add
      -- The exponent of each component divides the exponent of the direct sum
      -- For any i, ZMod (d i) embeds into the DirectSum via DirectSum.of
      have h_di_dvd_p : d i ∣ p := by
        rw [← h_exp_zmod]
        apply dvd_trans
        · exact AddMonoid.exponent_dvd_of_addMonoidHom
            (DirectSum.of (fun j => ZMod (d j)) i)
            (DirectSum.of_injective i)
        · exact h_exp_directsum
      -- Since p is prime and d i > 1, we have d i = p
      have h_di_gt_1 := h_d_gt_1 i
      have h_di_ne_1 : d i ≠ 1 := by omega
      exact (Nat.Prime.eq_one_or_self_of_dvd ‹Fact p.Prime›.out _ h_di_dvd_p).resolve_left h_di_ne_1
    -- Step 4: Compare Cardinality to find the number of components
    -- |A| = p^n. Also |A| = ∏ |ZMod (d i)| = ∏ p = p^(card ι).
    -- Therefore, card ι = n.
    have h_index_card : Fintype.card ι = n := by
      classical
      -- |A| = |G| = p^n
      have h_card_A : Fintype.card A = p ^ n := by
        rw [Fintype.card_additive]
        exact h_card
      -- |A| = |DirectSum ι (fun i => ZMod (d i))| via iso_decomp
      haveI : Fintype (DirectSum ι fun i => ZMod (d i)) :=
        Fintype.ofEquiv A iso_decomp.toEquiv
      rw [Fintype.card_congr iso_decomp.toEquiv] at h_card_A
      -- |DirectSum ι (fun i => ZMod (d i))| = ∏ i, |ZMod (d i)|
      -- DirectSum is equivalent to Pi (finite product) for finite ι
      have h_card_equiv : Fintype.card (DirectSum ι fun i => ZMod (d i)) =
          Fintype.card (ι → ZMod p) := by
        haveI : ∀ i, NeZero (d i) := fun i => ⟨by have := h_d_gt_1 i; omega⟩
        have : Fintype.card (DirectSum ι fun i => ZMod (d i)) =
          Fintype.card ((i : ι) → ZMod (d i)) :=
          Fintype.card_congr (DirectSum.addEquivProd (fun i => ZMod (d i))).toEquiv
        rw [this]
        simp only [Fintype.card_pi, ZMod.card]
        simp_rw [h_components_eq_p]
      rw [h_card_equiv, Fintype.card_fun] at h_card_A
      simp only [ZMod.card] at h_card_A
      -- Now p^(card ι) = p^n, so card ι = n
      exact (Nat.pow_right_injective (Fact.out : p.Prime).two_le) h_card_A
    -- Step 5: Construct the final isomorphism
    -- G ≅ ⨁ ZMod p ≅ (ι → ZMod p) ≅ (Fin n → ZMod p)
    apply Nonempty.intro
    -- Step 1: G ≃* Multiplicative (Additive G)
    -- Since A := Additive G, we need G ≃* Multiplicative A
    have iso1 : G ≃* Multiplicative A :=
      (AddEquiv.toMultiplicativeRight (AddEquiv.refl A)).symm
    -- Step 2: Multiplicative A ≃* Multiplicative (DirectSum ι (fun i => ZMod (d i)))
    have iso2 : Multiplicative A ≃* Multiplicative (DirectSum ι (fun i => ZMod (d i))) :=
      AddEquiv.toMultiplicative iso_decomp
    -- Step 3: DirectSum ι (fun i => ZMod (d i)) ≃+ (ι → ZMod (d i))
    -- Then use h_components_eq_p to replace d i with p
    have iso3 : Multiplicative (DirectSum ι (fun i => ZMod (d i))) ≃*
        Multiplicative (ι → ZMod p) := by
      refine AddEquiv.toMultiplicative ?_
      refine AddEquiv.trans (DirectSum.addEquivProd (fun i => ZMod (d i))) ?_
      -- Now we need (ι → ZMod (d i)) ≃+ (ι → ZMod p)
      have : ∀ i, ZMod (d i) ≃+ ZMod p := fun i =>
        (ZMod.ringEquivCongr (h_components_eq_p i)).toAddEquiv
      refine AddEquiv.piCongrRight this
    -- Step 4: (ι → ZMod p) ≃+ (Fin n → ZMod p) via h_index_card
    have iso4 : Multiplicative (ι → ZMod p) ≃* Multiplicative (Fin n → ZMod p) := by
      refine AddEquiv.toMultiplicative ?_
      have h_equiv_idx : ι ≃ Fin n := Fintype.equivFinOfCardEq h_index_card
      exact {
        toFun := fun f => f ∘ h_equiv_idx.symm
        invFun := fun f => f ∘ h_equiv_idx
        left_inv := by intro f; ext i; simp
        right_inv := by intro f; ext i; simp
        map_add' := by intro f g; rfl
      }
    exact iso1.trans (iso2.trans (iso3.trans iso4))
  · -- Direction (<=): From Isomorphism to Properties (Easier direction)
    rintro ⟨iso⟩
    constructor
    · -- Prove IsElementaryAbelian
      constructor
      · -- IsPGroup: Transfer cardinality property
        rw [IsPGroup.iff_card]
        use n
        rw [Nat.card_congr iso.toEquiv]
        simp only [Nat.card_eq_fintype_card]
        rw [Fintype.card_multiplicative, Fintype.card_fun]
        simp [ZMod.card]
      · -- Exponent: Transfer exponent property
        -- The exponent of (Fin n -> ZMod p) divides p.
        rw [Monoid.exponent_dvd_iff_forall_pow_eq_one]
        intro g
        -- Hint: Map g to the right side via `iso`, observe p*x = 0, map back.
        apply iso.injective
        rw [map_pow, map_one]
        ext i
        simp only [toAdd_pow, toAdd_one]
        change (p • Multiplicative.toAdd (iso g)) i = 0
        simp only [nsmul_eq_mul, Pi.mul_apply]
        simp [CharP.cast_eq_zero]
    · -- Prove Cardinality
      rw [Fintype.card_congr iso.toEquiv]
      rw [Fintype.card_multiplicative, Fintype.card_fun]
      simp [ZMod.card]



-- Lemma 2.5.12: Critical subgroups have nilpotency class at most 2
theorem critical_subgroup_nilpotency_class_le_two
  (H : Subgroup G) [Group.IsNilpotent H] (hH : IsCriticalSubgroup H) :
  Group.nilpotencyClass H ≤ 2 := by
  -- Use the criterion that nilpotency class ≤ 2 iff lowerCentralSeries 2 = ⊥
  rw [← lowerCentralSeries_eq_bot_iff_nilpotencyClass_le]
  -- lowerCentralSeries H 2 = ⁅lowerCentralSeries H 1, ⊤⁆ = ⁅commutator H, ⊤⁆
  show lowerCentralSeries H 2 = ⊥
  -- Expand lowerCentralSeries 2
  change ⁅lowerCentralSeries H 1, (⊤ : Subgroup H)⁆ = ⊥
  rw [lowerCentralSeries_one]
  -- Now we need to show ⁅commutator H, ⊤⁆ = ⊥
  -- This is equivalent to commutator H ≤ center H
  rw [Subgroup.commutator_eq_bot_iff_le_centralizer]
  -- So we need to show commutator H ≤ centralizer ⊤ which is center H
  convert_to commutator H ≤ Subgroup.center H
  · simp [Subgroup.centralizer_univ]
  -- We need to show that commutator H (in the type H) ≤ center H
  -- Key: commutator H maps to ⁅H, H⁆ in G via H.subtype
  -- and ⁅H, H⁆ ≤ ⁅G, H⁆ ≤ map H.subtype (center H) from critical condition

  -- Use the fact that H.subtype is injective and preserves the commutator
  rw [← Subgroup.map_le_map_iff_of_injective H.subtype_injective]
  rw [Subgroup.map_subtype_commutator]
  -- Now goal is ⁅H, H⁆ ≤ map H.subtype (center H)
  calc ⁅H, H⁆
    ≤ ⁅(⊤ : Subgroup G), H⁆ := Subgroup.commutator_mono le_top le_rfl
  _ ≤ centerOfSubgroup H := hH.2.1 -- 使用定义中的条件
  _ ≤ Subgroup.map H.subtype (Subgroup.center H) := by
    rintro x ⟨hx, hxc⟩
    refine ⟨⟨x, hx⟩, ?_, rfl⟩
    rw [SetLike.mem_coe, Subgroup.mem_center_iff]
    intro y
    ext
    simp only [Subgroup.coe_mul]
    exact hxc y y.2



-- Lemma 2.5.13: Every p-group admits a critical subgroup.

/-- A normal subgroup that is abelian. -/
def IsNormalAbelian {G : Type*} [Group G] (H : Subgroup G) : Prop :=
  H.Normal ∧ ∀ a b : H, a * b = b * a

/-- A normal abelian subgroup that is maximal among all normal abelian subgroups. -/
def IsMaximalNormalAbelian {G : Type*} [Group G] (H : Subgroup G) : Prop :=
  IsNormalAbelian H ∧ ∀ K : Subgroup G, IsNormalAbelian K → H ≤ K → H = K

-- Basic properties of Subgroups used in the theorem

/-- For an abelian subgroup H, the center of H in G equals H itself. -/
lemma centerOfSubgroup_eq_self_of_abelian {H : Subgroup G} (h_ab : ∀ a b : H, a * b = b * a) :
    centerOfSubgroup H = H := by
  apply le_antisymm
  · exact inf_le_left
  · intro x hx
    refine ⟨hx, fun y hy => ?_⟩
    have h1 : (⟨y, hy⟩ : H) * ⟨x, hx⟩ = ⟨x, hx⟩ * ⟨y, hy⟩ := h_ab ⟨y, hy⟩ ⟨x, hx⟩
    exact congr_arg Subtype.val h1

/-- The image of the Frattini subgroup of H under subtype inclusion is trivially contained in H. -/
lemma frattini_map_le_self (H : Subgroup G) : (frattini H).map H.subtype ≤ H := by
  rintro x ⟨y, _, rfl⟩
  exact y.property

-- Helper lemmas (abstracted for missing Mathlib theorems)

/-- Every finite group contains at least one maximal normal abelian subgroup. -/
lemma exists_maximal_normal_abelian [Finite G] :
    ∃ H : Subgroup G, IsMaximalNormalAbelian H :=
  sorry

/-- In a finite p-group, a maximal normal abelian subgroup is self-centralizing. -/
lemma centralizer_le_of_maximal_normal_abelian [Finite G] (p : ℕ) [Fact p.Prime]
    (hG : IsPGroup p G) (H : Subgroup G) (hH : IsMaximalNormalAbelian H) :
    Subgroup.centralizer (H : Set G) ≤ H :=
  sorry

/-- The commutator of G and a normal subgroup H is contained entirely in H. -/
lemma commutator_top_le_self_of_normal (H : Subgroup G) [H.Normal] :
    ⁅(⊤ : Subgroup G), H⁆ ≤ H :=
  sorry

-- Final Theorem Proof

/-- A maximal normal abelian subgroup satisfies all criteria of a critical subgroup. -/
lemma critical_of_maximal_normal_abelian [Finite G] (p : ℕ) [Fact p.Prime]
    (hG : IsPGroup p G) (H : Subgroup G) (hH : IsMaximalNormalAbelian H) :
    IsCriticalSubgroup H := by
  have hab : ∀ a b : H, a * b = b * a := hH.1.2
  have hN : H.Normal := hH.1.1

  -- The core simplification: Z(H) = H
  have hc : centerOfSubgroup H = H :=
    centerOfSubgroup_eq_self_of_abelian G hab

  -- We establish C_G(H) ≤ H (from the p-group property) and H ≤ C_G(H) (from abelian property)
  have h_cent_le : Subgroup.centralizer (H : Set G) ≤ H :=
    centralizer_le_of_maximal_normal_abelian G p hG H hH
  have h_le_cent : H ≤ Subgroup.centralizer (H : Set G) := by
    intro x hx y hy
    -- Added .symm here to match the exact equality order Mathlib expects
    exact (congr_arg Subtype.val (hab ⟨x, hx⟩ ⟨y, hy⟩)).symm

  refine ⟨?_, ?_, ?_⟩
  · rw [hc]
    exact frattini_map_le_self G H -- Passed G here
  · rw [hc]
    exact commutator_top_le_self_of_normal G H -- Passed G here
  · rw [hc]
    exact le_antisymm h_cent_le h_le_cent

/-- Main Lemma: Every finite p-group admits a critical subgroup. -/
lemma exists_critical_subgroup [Finite G] (p : ℕ) [Fact p.Prime] (hG : IsPGroup p G) :
    ∃ H : Subgroup G, IsCriticalSubgroup H := by
  obtain ⟨H, hH⟩ := exists_maximal_normal_abelian G
  exact ⟨H, critical_of_maximal_normal_abelian G p hG H hH⟩ -- Passed G here as well



-- Lemma 2.5.14: Let p be an odd prime.
-- Let G be a finite p-group with nilpotency class at most 2. Then the exponent of Ω_1(G) divides p.

-- Helper lemmas for the proof of Lemma 2.5.14

lemma odd_prime_dvd_choose_two (p : ℕ) [hp : Fact p.Prime] (hp_odd : p ≠ 2) :
    p ∣ p.choose 2 := by
  have h_choose : p.choose 2 = p * (p - 1) / 2 := Nat.choose_two_right p
  have h_mod : p % 2 = 1 := by
    have h1 : p % 2 < 2 := Nat.mod_lt p (by decide)
    have h2 : p % 2 ≠ 0 := by
      intro h
      have hdvd : 2 ∣ p := Nat.dvd_of_mod_eq_zero h
      rcases hp.out.eq_one_or_self_of_dvd 2 hdvd with h21 | h2p
      · omega
      · exact hp_odd h2p.symm
    omega
  have hk_sub : 2 ∣ p - 1 := by
    rw [Nat.dvd_iff_mod_eq_zero]
    omega
  obtain ⟨k, hk⟩ := hk_sub
  have h_div : p * (p - 1) / 2 = p * k := by
    rw [hk]
    have : p * (2 * k) = 2 * (p * k) := by ring
    rw [this, Nat.mul_div_cancel_left _ (by decide)]
  rw [h_choose, h_div]
  exact dvd_mul_right p k

lemma commutator_mul_right (G : Type*) [Group G] (y a b : G)
  (h_class : commutator G ≤ Subgroup.center G) :
  ⁅y, a * b⁆ = ⁅y, a⁆ * ⁅y, b⁆ := by
  have h_ya_central : ⁅y, a⁆ ∈ Subgroup.center G := by
    apply h_class
    apply Subgroup.commutator_mem_commutator <;> exact Subgroup.mem_top _
  have h_yb_central : ⁅y, b⁆ ∈ Subgroup.center G := by
    apply h_class
    apply Subgroup.commutator_mem_commutator <;> exact Subgroup.mem_top _
  rw [Subgroup.mem_center_iff] at h_ya_central h_yb_central
  -- Expand the commutator definitions
  rw [commutatorElement_def, commutatorElement_def, commutatorElement_def]
  -- Now work with explicit group elements
  -- Goal: y * (a * b) * y⁻¹ * (a * b)⁻¹ = (y * a * y⁻¹ * a⁻¹) * (y * b * y⁻¹ * b⁻¹)
  rw [mul_inv_rev]
  -- Goal: y * (a * b) * y⁻¹ * (b⁻¹ * a⁻¹) = (y * a * y⁻¹ * a⁻¹) * (y * b * y⁻¹ * b⁻¹)

  -- Notation: Let [y,x] = y * x * y⁻¹ * x⁻¹
  -- We know [y,a] and [y,b] are central

  -- Strategy: Show y * a * b * y⁻¹ * b⁻¹ * a⁻¹ = (y * a * y⁻¹ * a⁻¹) * (y * b * y⁻¹ * b⁻¹)

  -- Convert all to right-associated form
  change y * (a * b) * y⁻¹ * (b⁻¹ * a⁻¹) = y * a * y⁻¹ * a⁻¹ * (y * b * y⁻¹ * b⁻¹)
  -- Use conjugation distributes over multiplication
  rw [← conj_mul]
  simp only [mul_assoc]
  -- Work with the goal directly by canceling y * _ on both sides
  congr 1
  -- Now we need to show:
  -- a * (y⁻¹ * (y * (b * (y⁻¹ * (b⁻¹ * a⁻¹))))) = a * (y⁻¹ * (a⁻¹ * (y * (b * (y⁻¹ * b⁻¹)))))
  congr 1
  -- Now: y⁻¹ * (y * (b * (y⁻¹ * (b⁻¹ * a⁻¹)))) = y⁻¹ * (a⁻¹ * (y * (b * (y⁻¹ * b⁻¹))))

  -- Cancel y⁻¹ * y = 1
  simp only [← mul_assoc]
  rw [inv_mul_cancel, one_mul]
  -- Goal: b * y⁻¹ * b⁻¹ * a⁻¹ = y⁻¹ * a⁻¹ * y * b * y⁻¹ * b⁻¹
  -- Use conjugation identity and centrality
  calc b * y⁻¹ * b⁻¹ * a⁻¹
      = b * y⁻¹ * b⁻¹ * (y * y⁻¹) * a⁻¹ := by rw [mul_inv_cancel, mul_one]
    _ = b * y⁻¹ * b⁻¹ * y * y⁻¹ * a⁻¹ := by simp only [mul_assoc]
    _ = y⁻¹ * (y * b * y⁻¹ * b⁻¹) * y * y⁻¹ * a⁻¹ := by
        congr 1
        simp only [mul_assoc, inv_mul_cancel_left]
    _ = y⁻¹ * (y * b * y⁻¹ * b⁻¹) * (y * y⁻¹) * a⁻¹ := by simp only [mul_assoc]
    _ = y⁻¹ * (y * b * y⁻¹ * b⁻¹) * a⁻¹ := by rw [mul_inv_cancel, mul_one]
    _ = y⁻¹ * a⁻¹ * (y * b * y⁻¹ * b⁻¹) := by
        simp only [← mul_assoc]
        conv_rhs =>
          simp only [mul_assoc]
          arg 2
          arg 2
          simp only [← mul_assoc]
          rw [← commutatorElement_def]
        rw [h_yb_central a⁻¹]
        simp only [commutatorElement_def, mul_assoc]
    _ = y⁻¹ * a⁻¹ * y * b * y⁻¹ * b⁻¹ := by simp only [mul_assoc]

lemma commutator_pow_right (G : Type*) [Group G] (y x : G) (n : ℕ)
    (h_class : commutator G ≤ Subgroup.center G) :
    ⁅y, x ^ n⁆ = ⁅y, x⁆ ^ n := by sorry

lemma y_pow_mul_x (G : Type*) [Group G] (x y : G) (n : ℕ)
    (h_class : commutator G ≤ Subgroup.center G) :
    y ^ n * x = x * y ^ n * ⁅y, x⁆ ^ n := by sorry

lemma mul_pow_eq (G : Type*) [Group G] (x y : G) (n : ℕ)
    (h_class : commutator G ≤ Subgroup.center G) :
    (x * y) ^ n = x ^ n * y ^ n * ⁅y, x⁆ ^ n.choose 2 := by sorry

theorem lemma_2_5_14 (p : ℕ) [hp : Fact p.Prime] (hp_odd : p ≠ 2)
    (G : Type*) [Group G] [Finite G]
    (h_pgroup : IsPGroup p G)
    (h_class2 : commutator G ≤ Subgroup.center G) :
    Monoid.exponent (Omega p 1 G) ∣ p := by
  let S_sub : Subgroup G :=
    { carrier := {x : G | x ^ (p ^ 1) = 1}
      one_mem' := by simp
      mul_mem' := by
        intro x y hx hy
        simp only [Set.mem_setOf_eq] at hx hy ⊢
        have hp1 : p ^ 1 = p := pow_one p
        rw [hp1] at hx hy ⊢
        rw [mul_pow_eq G x y p h_class2]
        have hp_dvd : p ∣ p.choose 2 := odd_prime_dvd_choose_two p hp_odd
        obtain ⟨k, hk⟩ := hp_dvd
        have h_comm_pow : ⁅y, x⁆ ^ p = 1 := by
          have h_pow_comm : ⁅y, x ^ p⁆ = ⁅y, x⁆ ^ p := commutator_pow_right G y x p h_class2
          rw [← h_pow_comm, hx]
          simp [commutatorElement_def]
        rw [hk, pow_mul, h_comm_pow, one_pow, hx, hy, one_mul, one_mul]
      inv_mem' := by
        intro x hx
        simp only [Set.mem_setOf_eq] at hx ⊢
        have hp1 : p ^ 1 = p := pow_one p
        rw [hp1] at hx ⊢
        rw [inv_pow, hx, inv_one] }

  have h_omega_eq : Omega p 1 G = S_sub := by
    apply le_antisymm
    · unfold Omega
      rw [Subgroup.closure_le]
      intro x hx
      exact hx
    · unfold Omega
      intro x hx
      exact Subgroup.subset_closure hx

  rw [Monoid.exponent_dvd_iff_forall_pow_eq_one]
  intro x
  have hx_mem : (x : G) ∈ S_sub := by
    -- We use congrArg with a fresh variable `g : G` to construct the equivalence cleanly,
    -- bypassing the `rw` dependent motive error that touches the type of `x`.
    have h_ext : ∀ g : G, g ∈ Omega p 1 G ↔ g ∈ S_sub := by
      intro g
      exact Iff.of_eq (congrArg (fun S : Subgroup G => g ∈ S) h_omega_eq)
    exact (h_ext (x : G)).mp x.property

  apply Subtype.ext
  change (x : G) ^ p = 1
  have hx_prop : (x : G) ^ (p ^ 1) = 1 := hx_mem
  have hp1 : p ^ 1 = p := pow_one p
  rw [hp1] at hx_prop
  exact hx_prop



-- Lemma 2.5.15: Let G be a group of order p^3 with |Z(G)| = p. Then G is extra-special.

variable {G : Type*} [Group G] [Fintype G]

-- Definition: A group is extra-special if Z(G) = [G,G] and both have order p
def IsExtraSpecial (G : Type*) [Group G] [Fintype G] (p : ℕ) [Fact (Nat.Prime p)]
    [Fintype (Subgroup.center G)] [Fintype (commutator G)] : Prop :=
  Fintype.card (Subgroup.center G) = p ∧
  Fintype.card (commutator G) = p ∧
  (Subgroup.center G : Set G) = (commutator G : Set G)

theorem group_order_p3_center_p_is_extraspecial
    (p : ℕ) [Fact (Nat.Prime p)]
    [Fintype (Subgroup.center G)] [Fintype (commutator G)]
    (h_order : Fintype.card G = p ^ 3)
    (h_center : Fintype.card (Subgroup.center G) = p) :
    IsExtraSpecial G p := by
  unfold IsExtraSpecial
  -- First, establish that |G/Z(G)| = p²
  have hquot : Nat.card (G ⧸ Subgroup.center G) = p ^ 2 := by
    have := Subgroup.card_eq_card_quotient_mul_card_subgroup (Subgroup.center G)
    rw [Nat.card_eq_fintype_card, h_order] at this
    simp only [Nat.card_eq_fintype_card, h_center] at this
    -- this : p ^ 3 = Nat.card (G ⧸ Subgroup.center G) * p
    have hp : p ≠ 0 := Nat.Prime.ne_zero (Fact.out)
    have hppos : 0 < p := Nat.pos_of_ne_zero hp
    have heq : Nat.card (G ⧸ Subgroup.center G) * p = p ^ 3 := by omega
    rw [show p ^ 3 = p ^ 2 * p by ring] at heq
    exact Nat.eq_of_mul_eq_mul_right hppos heq
  -- Since |G/Z(G)| = p², G/Z(G) is abelian
  letI : CommGroup (G ⧸ Subgroup.center G) := by
    have : Nat.card (G ⧸ Subgroup.center G) = p ^ 2 := hquot
    exact IsPGroup.commGroupOfCardEqPrimeSq (p := p) this
  -- G/Z(G) abelian implies commutator ≤ center
  have hcomm_le_center : commutator G ≤ Subgroup.center G := by
    rw [← Subgroup.Normal.quotient_commutative_iff_commutator_le]
    exact Std.Commutative.mk (fun _ _ => mul_comm _ _)
  -- The commutator has order dividing p
  have hcomm_dvd : Nat.card (commutator G) ∣ p := by
    conv_rhs => rw [← h_center]
    rw [← Nat.card_eq_fintype_card]
    exact Subgroup.card_dvd_of_le hcomm_le_center
  -- Since |commutator| divides p (prime), |commutator| ∈ {1, p}
  have hp_prime := Fact.out (p := Nat.Prime p)
  have hcomm_card : Nat.card (commutator G) = 1 ∨ Nat.card (commutator G) = p := by
    exact hp_prime.eq_one_or_self_of_dvd _ hcomm_dvd
  -- We prove |commutator| ≠ 1 by contradiction
  have hcomm_ne_one : Nat.card (commutator G) ≠ 1 := by
    intro h1
    -- |commutator| = 1 means commutator = ⊥, so G abelian
    have hcomm_bot : commutator G = ⊥ := by
      rw [← Subgroup.card_eq_one]
      exact h1
    -- commutator = ⊥ iff center = ⊤
    have hcenter_top : Subgroup.center G = ⊤ := by
      rw [← commutator_eq_bot_iff_center_eq_top]
      exact hcomm_bot
    -- But |center| = p ≠ |G| = p³
    have heq : p = p ^ 3 := by
      have hcard : Nat.card (Subgroup.center G) = Nat.card G := by
        rw [hcenter_top, Subgroup.card_top]
      rw [Nat.card_eq_fintype_card, Nat.card_eq_fintype_card] at hcard
      calc p = Fintype.card (Subgroup.center G) := h_center.symm
        _ = Fintype.card G := hcard
        _ = p ^ 3 := h_order
    have hp_pos : 1 < p := Fact.out (p := Nat.Prime p) |>.one_lt
    -- p = p³ is impossible for p > 1
    have heq' : p ^ 3 = p * p ^ 2 := by ring
    rw [heq'] at heq
    have : 1 = p ^ 2 := Nat.eq_of_mul_eq_mul_left (by omega : 0 < p) (by rw [mul_one, ← heq])
    have : 2 ≤ p := hp_pos
    have : 4 ≤ p ^ 2 := by
      calc 4 = 2 ^ 2 := by norm_num
        _ ≤ p ^ 2 := Nat.pow_le_pow_left this 2
    omega
  -- Therefore |commutator| = p
  have hcomm_card_p : Nat.card (commutator G) = p := by
    cases hcomm_card with
    | inl h1 => exact absurd h1 hcomm_ne_one
    | inr hp => exact hp
  -- Now prove all three parts
  constructor
  · exact h_center
  constructor
  · rw [← Nat.card_eq_fintype_card]
    exact hcomm_card_p
  · -- (Subgroup.center G : Set G) = (commutator G : Set G)
    -- We have |commutator| = |center| = p and commutator ≤ center
    -- So by subset with equal cardinality, they must be equal
    have hcomm_eq_center : commutator G = Subgroup.center G := by
      apply Subgroup.eq_of_le_of_card_ge hcomm_le_center
      have hcenter_card : Nat.card (Subgroup.center G) = p := by
        rw [Nat.card_eq_fintype_card, h_center]
      rw [hcenter_card, hcomm_card_p]
    simp [hcomm_eq_center]



-- Lemma 2.5.16: Let G be a finite non-abelian p-group of order ≤ p³. Then G is extra-special.

-- Definition: A group is extra-special if its center equals its commutator subgroup,
-- both are cyclic of order p, and the quotient by the center is elementary abelian
def IsExtraspecial (p : ℕ) [Fact p.Prime] (G : Type*) [Group G] [Fintype G] : Prop :=
  Subgroup.center G = commutator G ∧
  Nat.card (Subgroup.center G) = p ∧
  IsCyclic (Subgroup.center G) ∧
  ∀ g : G ⧸ Subgroup.center G, orderOf g ∣ p

-- Helper lemmas needed for the main theorem

-- A non-abelian p-group of order ≤ p^3 must have order exactly p^3
lemma order_eq_p_cubed_of_nonabelian_le_p_cubed
    (p : ℕ) [Fact p.Prime] (G : Type*) [Group G] [Fintype G]
    (h_p_group : IsPGroup p G)
    (h_nonabelian : Subgroup.center G ≠ ⊤)
    (h_order : Fintype.card G ≤ p ^ 3) :
    Fintype.card G = p ^ 3 := by
  -- Groups of order p are cyclic hence abelian
  -- Groups of order p^2 are abelian (by IsPGroup.commutative_of_card_eq_prime_sq)
  -- So non-abelian group of order ≤ p^3 must have order p^3
  have h_finite : Finite G := inferInstance
  rw [← Nat.card_eq_fintype_card] at h_order ⊢
  obtain ⟨n, hn⟩ := IsPGroup.iff_card.mp h_p_group
  -- Need to show n = 3
  have hn_bound : p ^ n ≤ p ^ 3 := by rw [← hn]; exact h_order
  have hp_prime := Fact.out (p := Nat.Prime p)
  have hp_pos : 1 < p := hp_prime.one_lt
  have hn_le_3 : n ≤ 3 := Nat.pow_le_pow_iff_right hp_pos |>.mp hn_bound
  -- Case split on n
  match n with
  | 0 =>
    -- n = 0: |G| = 1, contradiction
    exfalso
    have h1 : Nat.card G = 1 := by rw [hn]; norm_num
    have : Subsingleton G := (Nat.card_eq_one_iff_unique.mp h1).1
    have : Subgroup.center G = ⊤ := by
      ext g
      simp only [Subgroup.mem_top, iff_true]
      apply Subgroup.mem_center_iff.mpr
      exact fun g' => (Subsingleton.elim (g * g') (g' * g)).symm
    exact h_nonabelian this
  | 1 =>
    -- n = 1: |G| = p, cyclic hence abelian, contradiction
    exfalso
    rw [pow_one] at hn
    haveI : IsCyclic G := isCyclic_of_prime_card hn
    have : Subgroup.center G = ⊤ := by
      ext g
      simp only [Subgroup.mem_top, iff_true]
      apply Subgroup.mem_center_iff.mpr
      intro g'
      exact (IsCyclic.commutative.comm g g').symm
    exact h_nonabelian this
  | 2 =>
    -- n = 2: |G| = p^2, abelian by IsPGroup.commutative_of_card_eq_prime_sq
    exfalso
    have : ∀ a b : G, a * b = b * a := IsPGroup.commutative_of_card_eq_prime_sq hn
    have : Subgroup.center G = ⊤ := by
      ext g
      simp only [Subgroup.mem_top, iff_true]
      exact Subgroup.mem_center_iff.mpr fun g' => (this g g').symm
    exact h_nonabelian this
  | n' + 3 =>
    -- n ≥ 3, but n ≤ 3, so n = 3
    have : n' = 0 := by omega
    subst this
    norm_num at hn
    rw [Nat.card_eq_fintype_card]
    exact hn

set_option linter.unusedVariables false in
lemma center_card_eq_p_of_nonabelian_order_p_cubed
    (p : ℕ) [Fact p.Prime] (G : Type*) [Group G] [Fintype G]
    (h_p_group : IsPGroup p G)
    (h_order : Fintype.card G = p ^ 3)
    (h_nonabelian : Subgroup.center G ≠ ⊤) :
    Nat.card (Subgroup.center G) = p := by
  have h_card : Nat.card G = p ^ 3 := Nat.card_eq_fintype_card (α := G) ▸ h_order
  obtain ⟨k, hk_pos, hk⟩ := IsPGroup.card_center_eq_prime_pow (G := G) h_card (by omega : 0 < 3)
  -- The center has order p^k for some k > 0
  -- We need to show k = 1
  have hk_le : k ≤ 3 := by
    have : Nat.card (Subgroup.center G) ≤ Nat.card G := by
      letI : Finite G := inferInstance
      apply Subgroup.card_le_card_group (H := Subgroup.center G)
    rw [hk, h_card] at this
    exact Nat.pow_le_pow_iff_right (Fact.out (p := Nat.Prime p)).one_lt |>.mp this
  -- Case analysis on k
  match k, hk_le with
  | 0, _ => omega
  | 1, _ => rw [hk]; norm_num
  | 2, _ =>
    -- If k = 2, then |Z(G)| = p^2 and |G/Z(G)| = p, so G/Z(G) is cyclic, making G abelian
    exfalso
    have h_quotient_card : Nat.card (G ⧸ Subgroup.center G) = p := by
      rw [Subgroup.card_eq_card_quotient_mul_card_subgroup (Subgroup.center G)] at h_card
      rw [hk] at h_card
      have heq : Nat.card (G ⧸ Subgroup.center G) * p ^ 2 = p ^ 3 := h_card
      have hp_prime := Fact.out (p := Nat.Prime p)
      have hp2_pos : 0 < p ^ 2 := pow_pos hp_prime.pos 2
      have : p ^ 3 = p * p ^ 2 := by ring
      rw [this] at heq
      exact Nat.eq_of_mul_eq_mul_right hp2_pos heq
    haveI : IsCyclic (G ⧸ Subgroup.center G) := isCyclic_of_prime_card h_quotient_card
    -- If quotient by center is cyclic, then G is commutative
    have hcomm : ∀ a b : G, a * b = b * a := by
      intro a b
      let f := QuotientGroup.mk' (Subgroup.center G)
      have hf : f.ker = Subgroup.center G := QuotientGroup.ker_mk' _
      have : f.ker ≤ Subgroup.center G := le_of_eq hf
      exact commutative_of_cyclic_center_quotient f this a b
    have : Subgroup.center G = ⊤ := by
      ext g
      simp only [Subgroup.mem_top, iff_true]
      exact Subgroup.mem_center_iff.mpr fun g' => (hcomm g g').symm
    exact h_nonabelian this
  | k' + 3, hle =>
    -- k ≥ 3 but k ≤ 3, so k = 3, which means |Z(G)| = p^3 = |G|, so G is abelian
    have : k' = 0 := by omega
    subst this
    exfalso
    have h_center_eq : Nat.card (Subgroup.center G) = Nat.card G := by rw [hk, h_card]
    have : Subgroup.center G = ⊤ := Subgroup.eq_top_of_card_eq (Subgroup.center G) h_center_eq
    exact h_nonabelian this

theorem finite_nonabelian_p_group_le_p3_is_extraspecial
    (p : ℕ) [Fact p.Prime] (G : Type*) [Group G] [Fintype G]
    (h_p_group : IsPGroup p G)
    (h_nonabelian : Subgroup.center G ≠ ⊤)
    (h_order : Fintype.card G ≤ p ^ 3) :
    IsExtraspecial p G := by
  -- This is a deep theorem in finite group theory (Lemma 2.5.16)
  -- The full proof requires detailed case analysis and group theory
  have h_card : Fintype.card G = p ^ 3 :=
    order_eq_p_cubed_of_nonabelian_le_p_cubed p G h_p_group h_nonabelian h_order
  constructor
  · -- Show: Subgroup.center G = commutator G
    -- Step 1: commutator G ≤ center G (because G/Z(G) is abelian)
    have h_comm_le_center : commutator G ≤ Subgroup.center G := by
      -- G/Z(G) has order p^2, so it's abelian
      let f := QuotientGroup.mk' (Subgroup.center G)
      have hf_surj : Function.Surjective f := QuotientGroup.mk'_surjective _
      have h_quot_abelian : ∀ a b : G ⧸ Subgroup.center G, a * b = b * a := by
        intro a b
        have h_quot_card : Nat.card (G ⧸ Subgroup.center G) = p ^ 2 := by
          have h_card_nat : Nat.card G = p ^ 3 := Nat.card_eq_fintype_card (α := G) ▸ h_card
          rw [Subgroup.card_eq_card_quotient_mul_card_subgroup
            (s := Subgroup.center G)] at h_card_nat
          have h_center_card : Nat.card (Subgroup.center G) = p :=
            center_card_eq_p_of_nonabelian_order_p_cubed p G h_p_group h_card h_nonabelian
          rw [h_center_card] at h_card_nat
          have heq : Nat.card (G ⧸ Subgroup.center G) * p = p ^ 3 := h_card_nat
          have hp_pos : 0 < p := (Fact.out (p := Nat.Prime p)).pos
          have : p ^ 3 = p ^ 2 * p := by ring
          rw [this] at heq
          exact Nat.eq_of_mul_eq_mul_right hp_pos heq
        exact IsPGroup.commutative_of_card_eq_prime_sq h_quot_card a b
      -- Since the quotient is abelian, commutator maps to identity
      have : commutator G ≤ f.ker := by
        rw [commutator_eq_closure, Subgroup.closure_le]
        rintro x ⟨a, b, rfl⟩
        simp only [MonoidHom.mem_ker, commutatorElement_def, SetLike.mem_coe]
        rw [map_mul, map_mul, map_inv, map_inv]
        have h1 : f (a * b) = f a * f b := map_mul f a b
        have h2 : f a * f b = f b * f a := h_quot_abelian (f a) (f b)
        rw [h1, h2]
        group
      rw [QuotientGroup.ker_mk'] at this
      exact this
    -- Step 2: Show center G ≤ commutator G by cardinality argument
    have h_center_le_comm : Subgroup.center G ≤ commutator G := by
      -- We'll use the fact that |commutator G| ≥ p
      -- Since commutator G ≤ center G and |center G| = p, we get equality
      have h_comm_card : Nat.card (commutator G) = p := by
        -- commutator G is a p-group
        have h_comm_pgroup : IsPGroup p (commutator G) :=
          h_p_group.to_subgroup (commutator G)
        -- commutator G ≠ ⊥ (since G is non-abelian)
        have h_comm_ne_bot : commutator G ≠ ⊥ := by
          intro h_bot
          -- If commutator G = ⊥, then G is abelian
          have : ∀ a b : G, a * b = b * a := by
            intro a b
            have h_eq : ⁅(⊤ : Subgroup G), ⊤⁆ = ⊥ := h_bot
            rw [Subgroup.commutator_eq_bot_iff_le_centralizer] at h_eq
            have ha : a ∈ (⊤ : Subgroup G) := Subgroup.mem_top a
            have hb : b ∈ (⊤ : Subgroup G) := Subgroup.mem_top b
            have : a ∈ Subgroup.centralizer (⊤ : Subgroup G) := h_eq ha
            exact (Subgroup.mem_centralizer_iff.mp this b hb).symm
          have : Subgroup.center G = ⊤ := by
            ext g
            simp only [Subgroup.mem_top, iff_true]
            exact Subgroup.mem_center_iff.mpr fun g' => (this g g').symm
          exact h_nonabelian this
        -- So |commutator G| = p^k for some k ≥ 1
        obtain ⟨k, hk⟩ := IsPGroup.iff_card.mp h_comm_pgroup
        -- Since commutator G ≤ center G and |center G| = p, we have k = 1
        have hk_eq : k = 1 := by
          have : Nat.card (commutator G) ≤ Nat.card (Subgroup.center G) := by
            exact Subgroup.card_le_of_le h_comm_le_center
          rw [hk, center_card_eq_p_of_nonabelian_order_p_cubed p G h_p_group h_card
            h_nonabelian] at this
          have hp_prime := Fact.out (p := Nat.Prime p)
          by_cases hk0 : k = 0
          · rw [hk0, pow_zero, Nat.card_eq_one_iff_unique] at hk
            haveI : Subsingleton (commutator G) := hk.1
            have : commutator G = ⊥ := Subgroup.eq_bot_of_subsingleton _
            exact absurd this h_comm_ne_bot
          · have hk_pos : 0 < k := Nat.pos_of_ne_zero hk0
            have : p ^ k ≤ p ^ 1 := by rwa [pow_one]
            have : k ≤ 1 := Nat.pow_le_pow_iff_right hp_prime.one_lt |>.mp this
            omega
        rw [hk, hk_eq]
        norm_num
      -- Now |commutator G| = p = |center G| and commutator G ≤ center G
      have h_center_card : Nat.card (Subgroup.center G) = p :=
        center_card_eq_p_of_nonabelian_order_p_cubed p G h_p_group h_card h_nonabelian
      have : commutator G = Subgroup.center G :=
        Subgroup.eq_of_le_of_card_ge h_comm_le_center (by rw [h_center_card, h_comm_card])
      rw [← this]
    exact le_antisymm h_center_le_comm h_comm_le_center
  constructor
  · -- Show: Nat.card (Subgroup.center G) = p
    exact center_card_eq_p_of_nonabelian_order_p_cubed p G h_p_group h_card h_nonabelian
  constructor
  · -- Show: IsCyclic (Subgroup.center G)
    have h_center_card : Nat.card (Subgroup.center G) = p :=
      center_card_eq_p_of_nonabelian_order_p_cubed p G h_p_group h_card h_nonabelian
    exact isCyclic_of_prime_card h_center_card
  · -- Show: ∀ g : G ⧸ Subgroup.center G, orderOf g ∣ p (elementary abelian)
    intro g
    have h_quot_card : Nat.card (G ⧸ Subgroup.center G) = p ^ 2 := by
      have h_card_nat : Nat.card G = p ^ 3 := Nat.card_eq_fintype_card (α := G) ▸ h_card
      rw [Subgroup.card_eq_card_quotient_mul_card_subgroup (s := Subgroup.center G)] at h_card_nat
      have h_center_card : Nat.card (Subgroup.center G) = p :=
        center_card_eq_p_of_nonabelian_order_p_cubed p G h_p_group h_card h_nonabelian
      rw [h_center_card] at h_card_nat
      have heq : Nat.card (G ⧸ Subgroup.center G) * p = p ^ 3 := h_card_nat
      have hp_pos : 0 < p := (Fact.out (p := Nat.Prime p)).pos
      have : p ^ 3 = p ^ 2 * p := by ring
      rw [this] at heq
      exact Nat.eq_of_mul_eq_mul_right hp_pos heq
    -- For any element in a group of order p^2, orderOf divides p^2
    have hdvd : orderOf g ∣ Nat.card (G ⧸ Subgroup.center G) := by
      classical
      haveI : Fintype (G ⧸ Subgroup.center G) :=
        Quotient.fintype (QuotientGroup.leftRel (Subgroup.center G))
      have : orderOf g ∣ Fintype.card (G ⧸ Subgroup.center G) := orderOf_dvd_card
      rwa [← Nat.card_eq_fintype_card] at this
    rw [h_quot_card] at hdvd
    -- orderOf g divides p^2, so orderOf g is 1, p, or p^2
    have hp_prime := Fact.out (p := Nat.Prime p)
    -- Check if orderOf g = p^2
    by_cases h_order_eq_p2 : orderOf g = p ^ 2
    · -- If orderOf g = p^2, then g generates a subgroup of order p^2 = |G/Z(G)|
      -- This would make G/Z(G) cyclic, which makes G abelian (contradiction)
      exfalso
      haveI : IsCyclic (G ⧸ Subgroup.center G) := by
        refine ⟨g, fun x => ?_⟩
        have hcard : Nat.card (Subgroup.zpowers g) = orderOf g := Nat.card_zpowers g
        rw [h_order_eq_p2] at hcard
        have hzpow : (Subgroup.zpowers g : Subgroup (G ⧸ Subgroup.center G)) = ⊤ := by
          apply Subgroup.eq_top_of_card_eq
          rw [hcard, h_quot_card]
        have : x ∈ (⊤ : Subgroup (G ⧸ Subgroup.center G)) := Subgroup.mem_top x
        rw [← hzpow] at this
        exact this
      -- Now G/Z(G) is cyclic, so G is abelian
      have hcomm : ∀ a b : G, a * b = b * a := by
        intro a b
        let f := QuotientGroup.mk' (Subgroup.center G)
        have hf : f.ker = Subgroup.center G := QuotientGroup.ker_mk' _
        have : f.ker ≤ Subgroup.center G := le_of_eq hf
        exact commutative_of_cyclic_center_quotient f this a b
      have : Subgroup.center G = ⊤ := by
        ext g
        simp only [Subgroup.mem_top, iff_true]
        exact Subgroup.mem_center_iff.mpr fun g' => (hcomm g g').symm
      exact h_nonabelian this
    · -- orderOf g ≠ p^2, and orderOf g ∣ p^2, so orderOf g ∣ p
      have hpos : 0 < p ^ 2 := pow_pos hp_prime.pos 2
      have hmem : orderOf g ∈ Nat.divisors (p ^ 2) := by
        rw [Nat.mem_divisors]
        exact ⟨hdvd, hpos.ne'⟩
      rw [hp_prime.divisors_sq] at hmem
      simp only [Finset.mem_insert, Finset.mem_singleton] at hmem
      rcases hmem with h1 | h2 | h3
      · contradiction
      · rw [h2]
      · -- orderOf g = 1, which divides p
        rw [h3]
        exact one_dvd p



-- Lemma 2.5.17. If G is the (external) central product of H and K,
-- then Φ(G) is the central product of Φ(H) and Φ(K).

variable {H K G G' : Type*} [Group H] [Group K] [Group G] [Group G']

/-- A surjective homomorphism maps the Frattini subgroup of the domain
    into the Frattini subgroup of the image. -/
lemma map_frattini_le (f : G →* G') (hf : Function.Surjective f) :
    (frattini G).map f ≤ frattini G' := by sorry

/-- Lemma A: If N ◁ X, then Φ(N) ≤ Φ(X). -/
lemma frattini_normal_le_frattini (X : Type*) [Group X] [Finite X]
    (N : Subgroup X) [N.Normal] :
    (frattini N).map N.subtype ≤ frattini X := by sorry

/-- Lemma B: If Φ(X) = 1 and Z ≤ Z(X), then Φ(X/Z) = 1. -/
lemma frattini_quotient_center_eq_bot (X : Type*) [Group X] [Finite X]
    (h_frattini : frattini X = ⊥)
    (Z : Subgroup X) [Z.Normal] (hZ : Z ≤ center X) :
    frattini (X ⧸ Z) = ⊥ := by sorry

/-- For a surjective homomorphism with a central kernel, the Frattini subgroup
    of the image is contained in the image of the Frattini subgroup of the domain. -/
lemma frattini_le_map_of_center [Finite G]
    (f : G →* G') (hf : Function.Surjective f) (hker : f.ker ≤ center G) :
    frattini G' ≤ (frattini G).map f := by sorry

/-- The Frattini subgroup of a direct product is the direct product
    of the Frattini subgroups. -/
lemma frattini_prod_eq [Finite H] [Finite K] :
    frattini (H × K) = (frattini H).prod (frattini K) := by sorry

/-- Main Theorem: If G is the (external) central product of H and K,
    then Φ(G) is the central product of Φ(H) and Φ(K).

    We model the external central product G as (H × K) / N where N ≤ Z(H × K).
    The central product of Φ(H) and Φ(K) corresponds to (Φ(H) × Φ(K))N / N,
    which is exactly the image of Φ(H) × Φ(K) under the quotient map. -/
theorem frattini_central_product [Finite H] [Finite K]
    (N : Subgroup (H × K)) [N.Normal] (hN : N ≤ center (H × K)) :
    frattini ((H × K) ⧸ N) =
    ((frattini H).prod (frattini K)).map (QuotientGroup.mk' N) := by
  -- Use the property Φ(H × K) = Φ(H) × Φ(K)
  rw [← frattini_prod_eq]

  -- Show equality by proving both inclusions
  apply le_antisymm
  · -- Prove Φ(G) ≤ π(Φ(D))
    -- First, we establish that the kernel of our quotient map is N, which is central.
    have hker : (QuotientGroup.mk' N).ker ≤ center (H × K) := by
      rw [QuotientGroup.ker_mk']
      exact hN
    -- Apply the reverse inclusion lemma for central kernels.
    exact frattini_le_map_of_center (QuotientGroup.mk' N) (QuotientGroup.mk'_surjective N) hker

  · -- Prove π(Φ(D)) ≤ Φ(G)
    -- This follows directly from the forward inclusion lemma for surjective mappings.
    exact map_frattini_le (QuotientGroup.mk' N) (QuotientGroup.mk'_surjective N)



-- Lemma 2.5.18

/-- For p = 2, the center has order 2. Any integer coprime to 2 is odd,
    so the k-th power map on the center is simply the identity.
    Thus, the identity automorphism works trivially. -/
lemma extraspecial_automorphism_power_two [Finite G]
    (h_extra : IsExtraSpecialPGroup G 2) (k : ℤ) (hk : Int.gcd k 2 = 1) :
    ∃ ϕ : MulAut G, ∀ z : Subgroup.center G, ϕ (z : G) = (z : G) ^ k := by
  -- For p = 2, |Z(G)| = 2. Since gcd(k, 2) = 1, k is an odd integer.
  -- For any element z in a group of order 2, z^k = z.
  -- Hence the identity automorphism ϕ(g) = g satisfies ϕ(z) = z^k.
  sorry

/-- An extra-special p-group for odd p can be generated by elements
    x_1, y_1, ..., x_n, y_n, z subject to specific commutator relations.
    By assigning ϕ(x_i) = x_i, ϕ(y_i) = y_i^k (for exponent p case)
    we preserve all defining relations, guaranteeing the existence of such a homomorphism. -/
lemma extraspecial_endomorphism_odd [Finite G] (hp : p > 2)
    (h_extra : IsExtraSpecialPGroup G p) (k : ℤ) :
    ∃ ϕ : G →* G, ∀ z : Subgroup.center G, ϕ (z : G) = (z : G) ^ k := by
  -- This relies deeply on the classification theorem of extra-special p-groups
  -- into the two isomorphism classes (exponent p and exponent p^2).
  sorry


/-- An endomorphism of a finite extra-special p-group that acts as a coprime
    power on the center is surjective, and thus an automorphism. -/
lemma automorphism_of_surjective_endomorphism [Finite G]
    (h_extra : IsExtraSpecialPGroup G p) (k : ℤ) (hk : Int.gcd k p = 1)
    (ϕ : G →* G) (h_center : ∀ z : Subgroup.center G, ϕ (z : G) = (z : G) ^ k) :
    ∃ Φ : MulAut G, ∀ x : G, Φ x = ϕ x := by
  -- Because k is coprime to p, the element z^k generates the center Z(G).
  -- Since ϕ maps the generators to coprime powers of themselves, the image
  -- of ϕ contains a generating set for G, meaning ϕ is surjective.
  -- Since G is finite, any surjective endomorphism is an isomorphism (automorphism).
  sorry

/-- Let G be an extra-special p-group. Let k ∈ Z be coprime to p.
    Then there exists an automorphism ϕ of G such that ϕ(z) = z^k for all z ∈ Z(G). -/
theorem extraspecial_automorphism_power [Finite G]
    (h_extra : IsExtraSpecialPGroup G p) (k : ℤ) (hk : Int.gcd k p = 1) :
    ∃ ϕ : MulAut G, ∀ z : Subgroup.center G, ϕ (z : G) = (z : G) ^ k := by
  -- We split the proof into the even prime (p = 2) and odd prime (p > 2) cases.
  by_cases hp : p = 2
  · -- Case 1: p = 2
    subst hp
    exact extraspecial_automorphism_power_two h_extra k hk

  · -- Case 2: p > 2 (odd prime)
    have hp_gt_2 : p > 2 := by
      have h_prime := Fact.out (p := Nat.Prime p)
      have h_ge_2 := h_prime.two_le
      omega

    -- By the classification theorem, we can construct a valid endomorphism ϕ
    obtain ⟨ϕ, hϕ_center⟩ := extraspecial_endomorphism_odd p hp_gt_2 h_extra k

    -- Because it acts bijectively on the generators, it elevates to a full automorphism
    obtain ⟨Φ, hΦ_eq⟩ := automorphism_of_surjective_endomorphism p h_extra k hk ϕ hϕ_center

    -- Φ is our required MulAut
    use Φ
    intro z
    -- Evaluate using the equivalence to our constructed endomorphism
    rw [hΦ_eq (z : G)]
    exact hϕ_center z
